title: gifmaker
description: Convert a series of images into a gif animation.
remote_theme: carlosperate/jekyll-theme-rtd

repo_url: "https://github.com/neuropoly/gifmaker"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
